export const enum TableEnum {
  USERS              = 'users',
  STUDENTS           = 'students',
  COURSES            = 'courses',
  TASKS              = 'tasks',
  QUESTIONS          = 'questions',
  ATTENDANCES        = 'attendances',
  GRADES             = 'grades',
  CATEGORIES         = 'categories',
  EVENTS             = 'events',
  CALENDAR_BY_MONTHS = 'calendar_by_months',
  STUDENT_TASK       = 'student_tasks',
  STUDENT_QUESTION   = 'student_questions',
  GRADE_REGISTER_AGGREGATES = 'grade_register_aggregates',
}
